

### 사원 조회
GET http://localhost:8080/mypage/memberInfo
Content-Type: application/json
Accept: */*


### 회원정보 변경을 위한 불러오기
GET http://localhost:8080/member/1
Content-Type: application/json
Accept: */*

### 회원 정보 수정하기
PUT http://localhost:8080/mypage/updatememberinfo
Content-Type: application/json
Accept: */*

{
  "employeeNo": 180,
  "name": "권지은",
  "employeeJoin": "2023-09-03T15:00:00.000+00:00",
  "employeeOut": null,
  "employeeEmail": "eun06151@naver.com",
  "employeePhone": "010-1234-1234",
  "employeeManager": 0,
  "reason": null,
  "annual": 0,
  "member": null,
  "department": "인사부",
  "position": "차장",
  "memberId": "Member221",
  "pw": "$2a$10$0TARWkrI3nMoVd5dvmkmKOru63Lqj8oDZCacyPv7/J7X7t3hvobLG",
  "memberNo": 240,
  "memberFile": "dfaa58382a7640219383978bbe40c887.jpg",
  "memberFileNo": 0,
  "memberState": null
}


### 회원 비밀번호 일치 체크
POST http://localhost:8080/mypage/checkpwd
Content-Type: application/json
Accept: */*

{ "memberNo": 41,
  "checkpw": "poyrdK9Ik7" }


### 회원 비밀번호 변경하기
PUT http://localhost:8080/mypage/changepwd
Content-Type: application/json
Accept: */*

{ "memberNo": 240,
"newpw": "qwer1234!!" }



### 회원 사진 변경하기
POST http://localhost:8080/mypage/empimg
Content-Type: application/json
Accept: */*

{
  "memberNo": 240,
  "originName": "3695ab85677d4adf80691f6c31474c1a.jpg",
  "memberFileNo": null,
  "memberState": null
}

### 회원의 사진파일 가져오기
GET http://localhost:8080/mypage/img/240
Content-Type: application/json
Accept: */*

### 매장 정보 가져오기
GET http://localhost:8080/member/store/220
Content-Type: application/json
Accept: */*

### 매장 정보 수정하기
PUT http://localhost:8080/mypage/updatestoreinfo
Content-Type: application/json
Accept: */*

{
  "storeNo": 80,
  "license": "60032146785",
  "address": " 서울 중구 ",
  "detailAddress": "낙원상가 1층",
  "email": "kim@gmail.com",
  "name": "김정국",
  "phone": "010-1234-1234",
  "storeFile": "3695ab85677d4adf80691f6c31474c1a.jpg",
  "pwd": "$2a$10$PUMrMmecrs7Iwaywkp4W5e00pAmkfJXAtj3fWkdyYXCOGsefdTOUy",
  "id": "Store219",
  "role": "STORE",
  "memberNo": 220
}