### 메일 조회
GET http://localhost:8080/mail/41
Content-Type: application/json
Accept: */*

### 북마크 메일 조회
GET http://localhost:8080/mailBookmark
Content-Type: application/json
Accept: */*

### 보낸 메일 조회
GET http://localhost:8080/mailSent/41
Content-Type: application/json
Accept: */*

### 삭제
DELETE http://localhost:8080/mail
Content-Type: application/json
Accept: */*

### 메일 전송
POST http://localhost:8080/mail
Content-Type: application/json
Accept: */*

### 메일 상태값
PUT http://localhost:8080/mail
Content-Type: application/json
Accept: */*

{
  "mailNo": 78,
  "receiver": "김지수",
  "title": "제목4",
  "context": "내용4",
  "goDate": "2023-08-25T02:28:27.000+00:00",
  "status": "N"
}

### 회원 조회
GET http://localhost:8080/member/selectEmployee
Content-Type: application/json
Accept: */*


